# Generated by Django 5.1.2 on 2024-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_singupc_opp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singupc',
            new_name='Signupc',
        ),
    ]
