# Generated by Django 5.1.2 on 2024-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_singupc_signupc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupc',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signupc',
            old_name='psw',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='signupc',
            name='psw_repeat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
