# Generated by Django 5.1.2 on 2024-10-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_name_signupc_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupc',
            old_name='psw_repeat',
            new_name='password_repeat',
        ),
    ]
