# Generated by Django 5.1.2 on 2024-10-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_rename_psw_repeat_signupc_password_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupc',
            name='No',
            field=models.CharField(default=20, max_length=122),
            preserve_default=False,
        ),
    ]
