# Generated by Django 5.1.2 on 2024-10-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_signupc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupc',
            name='No',
            field=models.IntegerField(),
        ),
    ]
