# Generated by Django 5.1.2 on 2024-10-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_loginc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namet', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('food', models.CharField(max_length=122)),
                ('hour', models.IntegerField()),
                ('quantit', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Loginc',
        ),
    ]
